### ISSUE TITLE
Latest release build crash

### ISSUE THREAD

**Issue by Yetta1** [OpenTechEngine/OpenTechBFG#68]
Just built the source, all was successful, however the engine crashes at startup.

**Comment by kortemik** [comment]
which branch was that? master?

**Comment by BielBdeLuna** [comment]
is there a way in windows to see the messages of OTE's console? like how in Linux, if you start the app in a terminal, you can get the console messages in the terminal even when the app has crashed.

**Comment by Yetta1** [comment]
Yes it was master. I'll have to look up tuts for how to get messages out of the console on Windows, maybe through the powershell.

**Comment by DanielGibson** [comment]
I couldn't reproduce the crash with Win64 Release binaries built with MSVC2013.

To actually run the default map I had to push some files into the repo that were missing because .gitignore hid them.

BTW, running `OpenTechEngine.exe +set fs_basepath ../../` in OpenTechBFG/build/bin/ works fine on Windows too, so copying files around isn't needed anymore.

**Comment by Yetta1** [comment]
Cleaned the solution and rebuilt, OTE works again, however there i a possible bug, the engine locks up completely when I move the mouswheel, in fullscreen it locks up the system, needing a system restart.

**Comment by DanielGibson** [comment]
great

**Comment by kortemik** [comment]
locks up completely was an issue in the past with mousewheel caused by
there being not enough weapons defined. the c++ code for wheel weapon
switch didn't check that there is a weapon to switch to. might be the issue
here too. i think i worked with it in dhewm3

**Comment by Yetta1** [comment]
Closing this since kortemik has it listed in another issue.
