### ISSUE TITLE
Open Dynamics Engine VS Bullet Physics.

### ISSUE THREAD

**Issue by Yetta1** [OpenTechEngine/OpenTechBFG#69]
I noticed that D3 uses ODE for physics which lacks some features over Bullet Physics. I've noticed a lot of developers is switching to Bullet for games and other simulation software, even used in film. Blender also makes use of Bullet. So I was wondering if it would be better to replace ODE with Bullet. My main reasoning for this is to test model rigs in Blenders game engine, to get a more accurate preview of how it would react in OTE if Bullet is implemented. Here is a link to a short comparison:

http://blog.wolfire.com/2010/03/Comparing-ODE-and-Bullet

**Comment by DanielGibson** [comment]
it does not use ODE, doom3 has its own physics engine

**Comment by BielBdeLuna** [comment]
@Yetta1 the biggest problems would be to adapt the link between the physics engine and every entity that uses physics and also the AF system, idTechX uses it's own engine. We might lack a programmer who knows how to do it but, since we haven't created any def for moveables yet, we are in the best position to switch to another physics engine, back in d3 times the problem was referencing all the def moveables to the new values in bullet, but this seemed like an excuse I bet re-adapting the entities to another physics engine would be a far troublesome experience. it would be great to switch to bullet though.

**Comment by kortemik** [comment]
Anyone up to this? I have a big pile of cegui stuff waiting to be implemented.

**Comment by Yetta1** [comment]
I've started learning Opengl, SDL2 and Bullet now, maybe one day i'll look at the OTE code and see if I can help add Bullet. For cegui, i'd like to see a fps/gpu profiler. I had to redo the map because of a glitch that ruined, the new version is a lot bigger and more complex. Going to need the fps counter to see where I have to optimize it. I haven't tested png files yet, but saw that there is also a apng format for animated png files, I wonder if it would work as it would be useful for effects.

**Comment by kortemik** [comment]
i can help with the fps counter quite fast, and with hud soonish

**Comment by BielBdeLuna** [comment]
for animated textures you can use the animation system already present in idTechX, slide and stop and repeat, or even use multiple textures.

I wish I knew more about c++ to help out with the bullet integration.

**Comment by DanielGibson** [comment]
I'd like this issue tracker to only contain actual issues and tasks, but not so much discussions.

That's why I created **https://github.com/OpenTechEngine/Discussions/issues** to discuss ideas, offtopic things etc.
If an idea discussed there gets to a point where we decide that it could/should be implemented, we'll add an issue here with the relevant information.
