### ISSUE TITLE
Build instructions are inaccurate and fail

### ISSUE THREAD

**Issue by EricxDu** [OpenTechEngine/OpenTechBFG#80]
> cd neo/
> ./cmake-eclipse-linux-profile.sh

cmake scripts now appear to be in scripts/ not neo/. Instructions should be changed to the correct directory, and also add > chmod +x cmake-eclipse-linux-profile.sh so it can be executed. However, if I do this, I get the following error:

> CMake Error at libs/cegui/CMakeLists.txt:124 (add_subdirectory):
>  The source directory
>
> >    /home/eric/local/src/OpenTechBFG/libs/cegui/CEGUI.git
>
>  does not contain a CMakeLists.txt file.

**Comment by kortemik** [comment]
Hello,

I suggest we add COMPILING(.md) and describe needed steps there.

you need to run:

git submodule init
git submodule update

that will get the dependency libraries.

**Comment by BielBdeLuna** [comment]
why not just update the readme? I already proposed a change in a pull request which included some of this : https://github.com/OpenTechEngine/OpenTechBFG/pull/77

**Comment by EricxDu** [comment]
kortemik: that did the trick. It's compiling right now.
To be clear, to update the README what needs to be added is:
> git submodule init
> git submodule update
and note that the setup scripts are in scripts/. I used
> ../scripts/cmake-eclipse-linux-profile.sh

**Comment by DoomedNerd** [comment]
I'm getting compile errors coming from CEGUI when compiling with OTBFG. I'm using MSVC 10, which works with RBDoom 3 Bfg... was thinking I had the wrong version of CEGUI, but I'm using 0.8.4 - the latest...

**Comment by kortemik** [comment]
https://ci.appveyor.com/project/kortemik/opentechbfg

msvc2013 as above works

**Comment by DoomedNerd** [comment]
Kortemik, I was getting this error:
<code>
1>------ Build started: Project: OpenTechEngine, Configuration: Release Win32 ------
1>Build started 9/4/2015 7:18:43 AM.
1>InitializeBuildStatus:
1>  Creating "OpenTechEngine.dir\Release\OpenTechEngine.unsuccessfulbuild" because "AlwaysCreate" was specified.
1>CustomBuild:
1>  All outputs are up-to-date.
1>ClCompile:
1>  MainMenu.cpp
1>  Settings.cpp
1>..\..\neo\cegui\menu\MainMenu\Settings.cpp(61): error C2562: 'BFG::CEGUIMenu::Settings::hide' : 'void' function returning a value
1>          C:\Users\Dude\Desktop\DOOM-3\OpenTechBFG-master\neo\.\cegui/menu/MainMenu/Settings.h(34) : see declaration of 'BFG::CEGUIMenu::Settings::hide'
1>
1>Build FAILED.
1>
1>Time Elapsed 00:00:06.68
========== Build: 0 succeeded, 1 failed, 0 up-to-date, 0 skipped ==========
</code>

... and I had to change 2 or 3 lines of code in Settings.cpp:
<code> 
void Settings::RegisterHandlers()
{
	window->subscribeEvent(
		CEGUI::FrameWindow::EventCloseClicked,
		CEGUI::Event::Subscriber( &Settings::hide, this )
		//&Settings::hide,
		//( this )
	);
}

//void Settings::hide()
bool Settings::hide( const CEGUI::EventArgs& args )
{
	setVisible( false );
	return false;
}
</code>
and in Settings.h:
<code>
class Settings: public GameMenu
{

private:
	//void hide();
	bool hide( const CEGUI::EventArgs& args );
};
</code>
I lost some time without specific documents for the msvc2010 compilation of OTBFG, but viola ;)

Any who, wow! What a cool project. There seems to be some problem with it not properly shutting down when I hit the quit button or type 'quit' into the console. The '`' key gets printed to the console each time I toggle it on, and the Settings aren't implemented yet...

**Comment by Yetta1** [comment]
Has there been a change to the github system? For some reason the git shell doesn't recognize the submodule and update commands. It use to work, not sure what's going on, maybe it's just something with my installation.

**Comment by kortemik** [comment]
instructions updated by #88
